name: Deploy to gh-pages

on:
  push:
    branches: [ "main" ]

# ---- BƯỚC SỬA LỖI: CẤP QUYỀN GHI CHO WORKFLOW ----
permissions:
  contents: write
# ----------------------------------------------------

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist